const lang = {
	en: {
		search: "Search",
		placeholder: "What would you like to search today",
		footer: {
			ques: "Question? Call 000-800-919-1694",
			faq: "FAQ",
			help: "Help Center",
			term: "Term of Use",
			privacy: "Privacy",
			cookie: "Cookie Preferences",
			corporate: "Corporate Information",
		},
		login: {
			name: "Full Name",
			email: "Email Address",
			password: "Password",
			signUp: "Sign Up",
			signIn: "Sign In",
			forgot: "Forgot Password?",
			newToNet: "New to Netflix",
			already: "Already registered",
			signUpNow: "Sign Up Now",
			signInNow: "Sign In Now",
			learn: "Learn more",
		},
	},
	hi: {
		search: "खोज",
		placeholder: "आज आप क्या खोजना चाहेंगे?",
		footer: {
			ques: "सवाल? 000-800-919-1694 पर कॉल करें",
			faq: "सामान्य प्रश्न",
			help: "सहायता केंद्र",
			term: "उपयोग की शर्त",
			privacy: "गोपनीयता",
			cookie: "कुकी प्राथमिकताएँ",
			corporate: "कॉर्पोरेट जानकारी",
		},
		login: {
			name: "पूरा नाम",
			email: "मेल पता",
			password: "पासवर्ड",
			signUp: "साइन अप करें",
			signIn: "दाखिल करना",
			forgot: "पासवर्ड भूल गए?",
			newToNet: "नेटफ्लिक्स पर नया",
			already: "पहले से ही पंजीकृत",
			signUpNow: "अभी साइनअप करें",
			signInNow: "अब साइन इन करो",
			learn: "और अधिक जानें",
		},
	},
	te: {
		search: "వెతకండి",
		placeholder: "మీరు ఈరోజు ఏమి శోధించాలనుకుంటున్నారు",
		footer: {
			ques: "ప్రశ్న? 000-800-919-1694కి కాల్ చేయండి",
			faq: "FAQ",
			help: "సహాయ కేంద్రం",
			term: "ఉపయోగ నిబంధన",
			privacy: "గోప్యత",
			cookie: "కుకీ ప్రాధాన్యతలు",
			corporate: "కార్పొరేట్ సమాచారం",
		},

		login: {
			name: "పూర్తి పేరు",
			email: "ఇమెయిల్ చిరునామా",
			password: "పాస్వర్డ్",
			signUp: "చేరడం",
			signIn: "సైన్ ఇన్ చేయండి",
			forgot: "పాస్‌వర్డ్ మర్చిపోయారా?",
			newToNet: "Netflixకి కొత్త",
			already: "ముందే నమోదుయాయ్యింది",
			signUpNow: "ఇప్పుడే సైన్ అప్",
			signInNow: "ఇప్పుడే సైన్ ఇన్ చేయండి",
			learn: "ఇంకా నేర్చుకో",
		},
	},
	ta: {
		search: "தேடல்",
		placeholder: "இன்று என்ன தேட விரும்புகிறீர்கள்",
		footer: {
			ques: "கேள்வி? 000-800-919-1694 ஐ அழைக்கவும்",
			faq: "FAQ",
			help: "உதவி மையம்",
			term: "பயன்பாட்டு விதிமுறை",
			privacy: "தனியுரிமை",
			cookie: "குக்கீ விருப்பத்தேர்வுகள்",
			corporate: "நிறுவன தகவல்",
		},

		login: {
			name: "முழு பெயர்",
			email: "மின்னஞ்சல் முகவரி",
			password: "கடவுச்சொல்",
			signUp: "பதிவு செய்யவும்",
			signIn: "உள்நுழையவும்",
			forgot: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
			newToNet: "Netflix க்கு புதியது",
			already: "ஏற்கனவே பதிவு செய்யப்பட்டது",
			signUpNow: "இப்பொது பதிவு செய்",
			signInNow: "இப்போது உள்நுழையவும்",
			learn: "மேலும் அறிக",
		},
	},
	es: {
		search: "buscar",
		placeholder: "¿Qué te gustaría buscar hoy?",
		footer: {
			ques: "¿Pregunta? Llame al 000-800-919-1694",
			faq: "FAQ",
			help: "Centro de ayuda",
			term: "Terminos de uso",
			privacy: "Privacidad",
			cookie: "Preferencias de cookies",
			corporate: "Información corporativa",
		},

		login: {
			name: "Nombre completo",
			email: "Dirección de correo electrónico",
			password: "Contraseña",
			signUp: "Inscribirse",
			signIn: "Iniciar sesión",
			forgot: "¿Has olvidado tu contraseña?",
			newToNet: "Nuevo en Netflix",
			already: "Ya registrado",
			signUpNow: "Regístrate ahora",
			signInNow: "Iniciar sesión ahora",
			learn: "Aprende más",
		},
	},
	gu: {
		search: "શોધ",
		placeholder: "તમે આજે શું શોધવા માંગો છો",
		footer: {
			ques: "પ્રશ્ન? 000-800-919-1694 પર કૉલ કરો",
			faq: "FAQ",
			help: "મદદ કેન્દ્ર",
			term: "ઉપયોગની મુદત",
			privacy: "ગોપનીયતા",
			cookie: "કૂકી પસંદગીઓ",
			corporate: "કોર્પોરેટ માહિતી",
		},

		login: {
			name: "પૂરું નામ",
			email: "ઈ - મેઈલ સરનામું",
			password: "પાસવર્ડ",
			signUp: "સાઇન અપ કરો",
			signIn: "સાઇન ઇન કરો",
			forgot: "પાસવર્ડ ભૂલી ગયા છો?",
			newToNet: "Netflix માટે નવું",
			already: "પહેલેથી નોંધાયેલ છે",
			signUpNow: "હમણાં સાઇન અપ કરો",
			signInNow: "હમણાં સાઇન ઇન કરો",
			learn: "વધુ શીખો",
		},
	},
	bn: {
		search: "অনুসন্ধান",
		placeholder: "আপনি আজ কি অনুসন্ধান করতে চান",
		footer: {
			ques: "প্রশ্ন? 000-800-919-1694 নম্বরে কল করুন",
			faq: "FAQ",
			help: "সাহায্য কেন্দ্র",
			term: "ব্যবহারের শর্ত",
			privacy: "গোপনীয়তা",
			cookie: "কুকি পছন্দ",
			corporate: "কর্পোরেট তথ্য",
		},

		login: {
			name: "পুরো নাম",
			email: "ইমেইল ঠিকানা",
			password: "পাসওয়ার্ড",
			signUp: "নিবন্ধন করুন",
			signIn: "সাইন ইন করুন",
			forgot: "পাসওয়ার্ড ভুলে গেছেন?",
			newToNet: "Netflix এ নতুন",
			already: "ইতিমধ্যে নিবন্ধভুক্ত",
			signUpNow: "এখন সাইন আপ করুন",
			signInNow: "এখন সাইন ইন করুন",
			learn: "আরও জানুন",
		},
	},
};

export default lang;
